# Generated by Django 4.0.6 on 2022-07-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=256)),
                ('opdate', models.CharField(max_length=256)),
                ('based', models.CharField(max_length=256)),
                ('hteam', models.CharField(max_length=256)),
                ('accnum', models.IntegerField()),
                ('location', models.CharField(max_length=256)),
                ('addrstmp', models.IntegerField()),
                ('addrkey', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'stadiums',
            },
        ),
    ]
