# Generated by Django 3.2.13 on 2022-07-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=256)),
                ('opdate', models.CharField(max_length=256)),
                ('based', models.CharField(max_length=256)),
                ('hteam', models.CharField(max_length=256)),
                ('accnum', models.IntegerField()),
                ('location', models.CharField(max_length=256)),
                ('addrstmp', models.IntegerField()),
                ('addrkey', models.CharField(max_length=256)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'stadium',
            },
        ),
    ]
