# Generated by Django 3.2.13 on 2022-07-12 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=18, unique=True)),
                ('passwd', models.CharField(max_length=18)),
                ('nickname', models.CharField(max_length=18)),
                ('team', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=18)),
                ('birth', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.TextField()),
                ('zipcode', models.IntegerField()),
                ('addr', models.TextField()),
                ('mailing', models.BooleanField(default=False)),
                ('regdate', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
