# Generated by Django 3.2.13 on 2022-07-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('home', models.TextField()),
                ('score', models.TextField()),
                ('away', models.TextField()),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
