# Generated by Django 3.2.13 on 2022-07-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('based', models.CharField(max_length=256)),
                ('hteam', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
