# Generated by Django 3.2.13 on 2022-07-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shopping',
            table='shopping',
        ),
    ]
