# Generated by Django 3.2.13 on 2022-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('regdate', models.CharField(max_length=20)),
                ('view', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-id'],
            },
        ),
    ]
