# Generated by Django 3.2.13 on 2022-07-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('name', models.TextField()),
                ('team', models.TextField()),
                ('goal', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('attackpoint', models.IntegerField()),
                ('losspoint', models.IntegerField()),
                ('cornerkick', models.IntegerField()),
                ('foul', models.IntegerField()),
                ('shoot', models.IntegerField()),
                ('offside', models.IntegerField()),
                ('warning', models.IntegerField()),
                ('exit', models.IntegerField()),
                ('norun', models.IntegerField()),
                ('trip', models.IntegerField()),
                ('replace', models.IntegerField()),
                ('matchpoint', models.FloatField()),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='Soccers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.TextField()),
                ('number', models.IntegerField()),
                ('name', models.TextField()),
                ('height', models.TextField()),
                ('kg', models.TextField()),
                ('birth', models.TextField()),
                ('position', models.TextField()),
            ],
            options={
                'db_table': 'soccers',
            },
        ),
    ]
